//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacecourseSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contests
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string HorsesBreed { get; set; }
        public Nullable<int> HorseAge { get; set; }
        public Nullable<long> PrizePool { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
