//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacecourseSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestParticipant
    {
        public int Id { get; set; }
        public int Contest_Id { get; set; }
        public int Horse_Id { get; set; }
        public int Jockey_Id { get; set; }
    }
}
