//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacecourseSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horses
    {
        public int Id { get; set; }
        public Nullable<int> HorseFactory_Id { get; set; }
        public Nullable<int> Trainer_Id { get; set; }
        public Nullable<int> Owner_Id { get; set; }
        public string Name { get; set; }
        public string Breed { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Country { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual HorseFactories HorseFactories { get; set; }
        public virtual HorseOwners HorseOwners { get; set; }
        public virtual Trainers Trainers { get; set; }
    }
}
