//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacecourseSystem.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RacecourseDBEntities : DbContext
    {
        public RacecourseDBEntities()
            : base("name=RacecourseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contests> Contests { get; set; }
        public virtual DbSet<HorseFactories> HorseFactories { get; set; }
        public virtual DbSet<HorseOwners> HorseOwners { get; set; }
        public virtual DbSet<Jockeys> Jockeys { get; set; }
        public virtual DbSet<Racecourses> Racecourses { get; set; }
        public virtual DbSet<Trainers> Trainers { get; set; }
    }
}
